name: Add Issues & PRs to GitHub Project Board

on:
  issues:
    types: [opened, reopened, labeled]
  pull_request:
    types: [opened, reopened, labeled]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      # 1. For all repos in ccmmf org
      - name: Add items from ccmmf org
        if: startsWith(github.repository, 'ccmmf/')
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/ccmmf/projects/4
          github-token: ${{ secrets.PAT_CCMMF_PROJECTS }}

      # 2. For the pecanproject/sipnet repo
      - name: Add items from pecanproject/sipnet
        if: github.repository == 'pecanproject/sipnet'
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/ccmmf/projects/4
          github-token: ${{ secrets.PAT_PECAN_PROJECTS }}

      # 3. For all other repos in pecanproject/*, only add items labeled "ccmmf"
      - name: Add items labeled ccmmf from pecanproject repos
        if: startsWith(github.repository, 'pecanproject/') && (github.repository != 'pecanproject/sipnet')
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/ccmmf/projects/4
          github-token: ${{ secrets.PAT_PECAN_PROJECTS }}
          labeled: ccmmf
          label-operator: OR
